services:
  postgres:
    container_name: social-db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgressql/postgres_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: social
      POSTGRES_PASSWORD: social
volumes:
  postgres_data: